version: 0.0
os: windows # windows도 linux로 하라고 나와있음. 아님!!! windows라고 해야함!!!
files:
  - source: /
    destination: C:\jumanji-service # 배포 파일 도착 폴더
    overwrite: yes 
    # 이 설정을 해도 덮어써지지 않는 다는 말이 있는데 저는 일단 잘되서 사용중입니다.
    # 제대로 되지않는다면, 아래 hooks BeforeInstall 를 추가하여, 존재하는 파일을 삭제하는 방법이 있습니다

#permissions:  #권한은 windows에서 지원 안함.
#  - object: /
#    pattern: "**" # 모든 파일의 권한 설정

hooks:
  BeforeInstall:
    - location: killport.bat
      timeout: 15
    - location: deletejar.bat
      timeout: 5
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.bat
      timeout: 70000
      # runas: root  windows에선 지원x